### ISSUE TITLE
Run npm install during build

### ISSUE THREAD

**Issue by adgroc** [kevinmgates/mslearn-tailspin-spacegame-web#11]
Need to run npm install as part of build. Here's the snippet from the Azure DevOps pipeline:

```
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        verbose: false
```
