### ISSUE TITLE
Add path filters to build

### ISSUE THREAD

**Issue by adgroc** [kevinmgates/mslearn-tailspin-spacegame-web#14]
Should look something like this:

```
on:
  push:
    branches:
      - master
    paths:
    - Tailspin.SpaceGame.Web/*
    - Tailspin.SpaceGame.Web.Tests/*
```
